kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: ride-sharing-cluster
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 8081
    hostPort: 8081
    protocol: TCP  # For API Gateway
  - containerPort: 9090
    hostPort: 9090
    protocol: TCP  # Assuming all services use this port, adjust if needed
# - role: worker
#   labels:
#     service: api-gateway
# - role: worker
#   labels:
#     service: user-service 